Write-Host "========================================" -ForegroundColor Cyan
Write-Host "     SLH TRADING BOT – HELP SYSTEM" -ForegroundColor Yellow
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "SLH (Smart Liquidity Harvester) is an autonomous crypto trading infrastructure."
Write-Host "It combines CEX (Binance), DEX (Web3), AI, and privacy (ZK, Railgun, Aztec)."
Write-Host ""
Write-Host "--- SYSTEM OVERVIEW ---"
Write-Host "  Main Bot    : Trades on Binance Testnet (paper money) with AI decisions."
Write-Host "  Supervisor  : Monitors system health, responds to Telegram commands."
Write-Host "  Doctor      : Full system diagnostic (.\slh-doctor.ps1)."
Write-Host "  API         : FastAPI on port 8080 (inside Docker)."
Write-Host "  UI Plan     : docs\slh-ui-plan.md (React + Tailwind)."
Write-Host ""
Write-Host "--- USER ROLES (RBAC) ---"
Write-Host "  viewer   : Read-only dashboard & trades."
Write-Host "  trader   : Start/stop bot, view trades."
Write-Host "  manager  : Trader + configure strategies & risk."
Write-Host "  admin    : Full access + user management."
Write-Host ""
Write-Host "--- QUICK COMMANDS ---"
Write-Host "  .\slh-master.ps1     : Show full system status & doctor."
Write-Host "  Show-SLHMenu         : Interactive control panel."
Write-Host "  .\restart.ps1        : Restart main bot (Docker)."
Write-Host "  .\slh-doctor.ps1     : Run system diagnostic."
Write-Host "  .\rotate_tokens.ps1  : Rotate API keys & Telegram tokens."
Write-Host "  .\agent_handoff.ps1  : Create package for UI developer."
Write-Host ""
Write-Host "--- RESUMING IN A NEW CHAT ---"
Write-Host "  Run: .\slh-master.ps1"
Write-Host "  Copy all output and paste to AI with:"
Write-Host "  'Here is the current system status of SLH. Continue from this point.'"
Write-Host ""
Write-Host "--- IMPORTANT FILES ---"
Write-Host "  .env            : All secrets (never commit!)"
Write-Host "  TASKS.md        : Master task list"
Write-Host "  docs\slh-ui-plan.md : Full UI/UX specification"
Write-Host "  docs\slh-project-management.md : Work methodology"
Write-Host ""
Write-Host "For more details, read the handoff document or contact @SLH_Supervisor_bot on Telegram."
Write-Host "========================================" -ForegroundColor Cyan
